version: "3.8"

services:
  # --- FRONTEND DEV ---
  client-dev:
    image: haiou2003/petshop-client:dev
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    profiles: ["dev"]

  # --- FRONTEND PROD ---
  client-prod:
    image: haiou2003/petshop-client:latest
    env_file:
      - ./client/.env.production
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    profiles: ["prod"]

  # --- BACKEND DEV ---
  server-dev:
    image: haiou2003/petshop-server:dev
    env_file:
      - ./server/.env
    ports:
      - "5001:5000"
    profiles: ["dev"]

  # --- BACKEND PROD ---
  server-prod:
    image: haiou2003/petshop-server:latest
    env_file:
      - ./server/.env.production
    ports:
      - "5000:5000"
    profiles: ["prod"]

  # --- RUN COMMAND FOR DEV ----
  # docker compose --profile dev up -d

  # --- RUN COMMAND FOR PROD ----
  # docker compose --profile prod up -d
