version: "3.8"

services:
  client:
    image: haiou2003/petshop-client:latest
    env_file:
      -  ./client/.env
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  server:
    image: haiou2003/petshop-server:latest
    env_file:
      -  ./server/.env
    ports:
      - "5000:5000"
