name: CI/CD PetShop (Client + Server with Docker + Test)

on:
  push:
    branches:
      - main
    paths:
      - 'PetShop/**'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # ======== CLIENT TEST ========
      - name: Install dependencies (Client)
        working-directory: PetShop/client
        run: npm ci

      - name: Run tests (Client)
        working-directory: PetShop/client
        run: npm test -- --watchAll=false --passWithNoTests

      # ======== SERVER TEST ========
      - name: Install dependencies (Server)
        working-directory: PetShop/server
        run: npm ci

      - name: Run tests (Server)
        working-directory: PetShop/server
        run: npm test -- --watchAll=false --passWithNoTests

      # ======== BUILD DOCKER IMAGES (PROD) ========
      - name: Build Client Image (Prod)
        run: |
          docker build \
            -f ./PetShop/client/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/petshop-client:latest \
            ./PetShop/client

      - name: Build Server Image (Prod)
        run: |
          docker build \
            -f ./PetShop/server/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/petshop-server:latest \
            ./PetShop/server

      # ======== BUILD DOCKER IMAGES (DEV) ========
      - name: Build Client Image (Dev)
        run: |
          docker build \
            -f ./PetShop/client/Dockerfile.dev \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/petshop-client:dev \
            ./PetShop/client

      - name: Build Server Image (Dev)
        run: |
          docker build \
            -f ./PetShop/server/Dockerfile.dev \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/petshop-server:dev \
            ./PetShop/server

      # ======== PUSH DOCKER IMAGES ========
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Client Image (Prod)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/petshop-client:latest

      - name: Push Server Image (Prod)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/petshop-server:latest

      - name: Push Client Image (Dev)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/petshop-client:dev

      - name: Push Server Image (Dev)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/petshop-server:dev

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-test-push
    steps:
      - name: SSH to VM & deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VM_HOST }}
            # Clone hoặc update repo
            if [ ! -d "/Typescript_Projects" ]; then
              git clone https://github.com/TTHai-Git/Typescript_Projects
            fi
            cd /Typescript_Projects/PetShop
            git reset --hard
            git pull origin main
          
            # Copy .env cho client và server
            echo "${{ secrets.CLIENT_ENV }}" > Typescript_Projects-main/PetShop/client/.env
            echo "${{ secrets.SERVER_ENV }}" > Typescript_Projects-main/PetShop/server/.env
          
            # Pull docker images
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/petshop-client:dev
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/petshop-server:dev
          
            # Chạy docker compose
            docker compose -f PetShop-docker-compose.yml --profile dev up -d
          
            # Xoá image không cần thiết
            docker image prune -f
