name: CI/CD PetShop (Client + Server with Docker + Test)

on:
  push:
    branches:
      - main
    paths:
      - 'PetShop/**'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # ======== CLIENT TEST ========
      - name: Install dependencies (Client)
        working-directory: PetShop/client
        run: npm ci

      - name: Run tests (Client)
        working-directory: PetShop/client
        run: npm test -- --watchAll=false

      # ======== SERVER TEST ========
      - name: Install dependencies (Server)
        working-directory: PetShop/server
        run: npm ci

      - name: Run tests (Server)
        working-directory: PetShop/server
        run: npm test -- --watchAll=false

      # ======== BUILD DOCKER IMAGES ========
      - name: Build Client Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/project1-client:latest \
            ./project1/client

      - name: Build Server Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/project1-server:latest \
            ./project1/server

      # ======== PUSH DOCKER IMAGES ========
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Client Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/PetShop-client:latest

      - name: Push Server Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/PetShop-server:latest
